export const ENV_VARS = {
  PORT: 'PORT',

  MONGO_DB_USER: 'MONGO_DB_USER',
  MONGO_DB_PASSWORD: 'MONGO_DB_PASSWORD',
  MONGO_DB_HOST: 'MONGO_DB_HOST',
  MONGO_DB_DATABASE: 'MONGO_DB_DATABASE',

  SMTP_PORT: 'SMTP_PORT',
  SMTP_HOST: 'SMTP_HOST',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASSWORD: 'SMTP_PASSWORD',
  SMTP_FROM: 'SMTP_FROM',

  FRONTEND_DOMAIN: 'FRONTEND_DOMAIN',
  JWT_SECRET: 'JWT_SECRET',
};
